spring:
  rabbitmq:
    host: 47.94.169.13
    port: 5675
    virtual-host: /
    username: user
    password: 111111
    publisher-confirms: true #如果对异步消息需要回调必须设置为true
  application:
    name: study-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/lanlingkeji_yu.jl/srpingcloudstudyconfig.git
server:
  port: 12000

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
